name: Build

on:
  push:
    tags:
      - "v*"
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm i --no-audit

      # Build script also run a type-check to ensure there are no type errors.
      - name: Build
        run: npm run build

      # Store the dist/ folder as an artifact to be used in the publish job.
      - name: Archive dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error
          compression-level: 0
