name: Build & type-check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm i --no-audit

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
