name: Build & type-check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build library
        run: pnpm --filter vue3-select-component run build

      - name: Test library
        run: pnpm --filter vue3-select-component run test

      - name: Build docs
        run: pnpm run docs:build
