# Release is automatically triggered when a new tag is pushed to the repository,
# this is done using `npm run bumpp`.
#
# This action will use `changelogithub` which generates a changelog using
# conventional commits, inside the GitHub release.
#
# See: https://github.com/antfu/changelogithub

name: Generate changelog

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  changelog:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
